// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Input struct {
	Name string `json:"name"`
}

type Setup struct {
	ClientID string `json:"clientId"`
	Audience string `json:"Audience"`
	Domain   string `json:"Domain"`
}
